### ISSUE TITLE
Display correct Category/Product name in condition Excluding block

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-marketing#11]
### Expected behavior
Selected Category/Product name displayed in condition Excluding block.

### Actual behavior
ID of selected Category/Product is displayed:
![image](https://user-images.githubusercontent.com/5801549/30914151-441929b0-a39b-11e7-85bc-41272683e8d4.png)

### Steps to reproduce
1. Create new promotion with excluding condition and category selected.
2. save the promotion
3. when the data is reloaded, ID of selected Category/Product is displayed.

**Comment by eMazeika** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-marketing/commit/54309d291c0035328e6503f43cca2494cad30b19 by requesting Category/Product info from server.

**Comment by tatarincev** [comment]
Found other visual bug for excluding elements 
![image](https://user-images.githubusercontent.com/7566324/31378325-2eb78ac0-adab-11e7-9589-fe98100ca22a.png)

**Comment by eMazeika** [comment]
@tatarincev  Are you providing some fake image here? Excluding for categories condition doesn't currently exist.
Pls, add this to relevant task, if we have such code/condition somewhere. Anyway, that's not related to this particular task.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.16.6
