### ISSUE TITLE
Coupon to have the maximum number of uses per registered user

### ISSUE THREAD

**Issue by ham8952** [VirtoCommerce/vc-module-marketing#12]
Hi guys i was just wondering if you guys could include in your next release a new way to configure a coupon to have the maximum number of uses per registered user. 
User case is "As a system admin i want to create a coupon that allows only one use for each of my registered users".

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-marketing/releases/v2.17.1
