### ISSUE TITLE
New promotions design feedback  

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-marketing#13]
- instead of "Exclusive with an order" the field should be displayed as "Exclusivity" with an options to choose from "Globally exclusive", "Can be combined with others".
- Combine with self is not needed (never encountered such promotions requirement)
- where are rules specified that negative values are not allowed?
- Are there perfromance indicators for promotions? Promotions evaluated per second?

**Comment by tatarincev** [comment]
Released with counting all of these remarks
https://virtocommerce.com/docs/vc2userguide/marketing/combine-active-promotions
