### ISSUE TITLE
Cannot set promotion end time

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-marketing#15]
Promotion end time is always set to 11:59:59 PM after saving changes, even if I selected different time.
![image](https://user-images.githubusercontent.com/8775253/35796615-cf18d930-0a65-11e8-87ca-8d997ce1c5c4.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.16.10
