### ISSUE TITLE
Limit the reward for relative discount

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-marketing#20]
Need a field to enter a maximum credit/discount for all relative rewards.
For example:
Get [ 10 ] % off [ select product ] not to exceed $ [ 500 ]
The field will accept a numeric dollar amount that will put a limit on the promotion.

**Comment by tatarincev** [comment]
Technical details:
- Extend  `AmountBasedReward.ThresholdAmount` https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.Domain/Marketing/Model/Promotions/Rewards/AmountBasedReward.cs
- Extend `RewardItemGetOfRel.TresholdAmount` https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/master/VirtoCommerce.DynamicExpressionsModule.Data/Promotion/Rewards/RewardItemGetOfRel.cs
- Extend `RewardItemGetOfRel` template with new `not to exceed` parameter https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/master/VirtoCommerce.DynamicExpressionsModule.Web/Scripts/all-templates.html#L203
- Use the new `TresholdAmount` in the  all `IDiscountable` domain entities  in the strorefront

**Comment by emathavan** [comment]
I see that your team made a commit to this ticket.  Thanks.  Is there an eta on when it is slated for a platform release.  We have a project launching in October and its a requirement for Go-Live.  Thanks!

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-module-dynamic-expressions/releases/v2.12.8
