### ISSUE TITLE
Looks like this line of code is redundant

### ISSUE THREAD

**Issue by doanson44** [VirtoCommerce/vc-module-marketing#206]
https://github.com/VirtoCommerce/vc-module-marketing/blob/bb702befc5edcc2ef581b5a84825ab51d69f7add/src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingRepository.cs#L49

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8293 has been created

**Comment by OlegoO** [comment]
@doanson44 
This code Asynchronously loads the collection of entities from the database. 
Need to replace ToArrayAsync with LoadAsync,

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/3.207.0
