### ISSUE TITLE
Make PromotionReward web model extendable

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-marketing#25]
When I create new reward types derived from domain model they are still being converted to the same web model `PromotionReward` which doesn't have my new fields:
``` csharp
public static webModel.PromotionReward ToWebModel(this coreModel.PromotionReward reward)
{
    var retVal = new webModel.PromotionReward();
    retVal.InjectFrom(reward);
   ...
```
So I cannot expose rewards with custom fields through the API.

Solution:
1. Create web model instances with AbstractTypeFactory.
2. Move converters to the models and make them virtual.
2. Move all web models with their converters to a separate project with minimal dependecies (say VirtoCommerce.MarketingModule.Web.Core) and create a NuGet package for it.

**Comment by asvishnyakov** [comment]
Or just don't use web models :)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.0
