### ISSUE TITLE
Show article/sku in promotion

### ISSUE THREAD

**Issue by ThePeterSan** [VirtoCommerce/vc-module-marketing#27]
Once you have chosen a product as a condition or reward, only the name of the product appears. It is also desirable that the article number be displayed.

**Comment by tatarincev** [comment]
Need to do something like this 
![image](https://user-images.githubusercontent.com/7566324/40645087-914e5724-6325-11e8-99fb-3a65f78bdb59.png)

The file where defined all templates used in marketing dynamic expressions
https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/master/VirtoCommerce.DynamicExpressionsModule.Web/Scripts/all-templates.html

**Comment by yecli** [comment]
Added [task](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/issues/14) to show codes to vc-module-dynamic-expressions.
This issue could be closed, as PR was already merged.
