### ISSUE TITLE
No validation on SEO URL to prevent duplicates/URL conflicts

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-module-marketing#38]
Virto team
We have a pressing request that should be quick for the Virto team to incorporate into the base code.  This to prevent us from development outside of core and keep us on the proper upgrade patch. The client is mandating this one for the 10/17 Go Live to production.  Issue is below.  Can this be accomodated rather quickly?

**Issue**
No validation on SEO URL to prevent duplicates/URL conflicts

**To Repro**
Create a new virtual category
Navigate to manage its SEO properties
Enter a URL that already exists
Note: no error is presented

**Expected result**:  Users should not be able to assign a URL to a category that conflicts with an existing.

![image](https://user-images.githubusercontent.com/37384557/44813341-91df0380-aba7-11e8-99dd-a18f44e22b78.png)
![image](https://user-images.githubusercontent.com/37384557/44813411-b3d88600-aba7-11e8-9ff4-6419a7707522.png)

**Comment by tatarincev** [comment]
VC has the SEO conflicts detection and resolution functionality.

UI prevents SEO conflicts at the concrete product (or category) within the concrete store level.

![image](https://user-images.githubusercontent.com/7566324/44846247-2ef57700-ac50-11e8-84ce-c54538cc2d8f.png)

Conflicting SEO detection is executed every time when you open a store in Manager UI. In case same duplicating SEOs are found, the red SEO widget comes into notice:

![image](https://user-images.githubusercontent.com/7566324/44846468-b3e09080-ac50-11e8-88fd-7d312b42ac0c.png)

SEOs list now has an informer describing the problem. Click "Resolve conflicts" and fix the duplicating SEOs quickly by updating semantic URL(s):

![image](https://user-images.githubusercontent.com/7566324/44846271-387edf00-ac50-11e8-9ef0-8afaf3fbff4d.png)

In this article, you can read more about SEO URL routing on storefront works http://virtocommerce.com/docs/vc2devguide/working-with-storefront/storefront-seo-routing.

@emathavan Please check is this  functionality works for you?

**Comment by emathavan** [comment]
Tatarincev
We have a 10/17 project launch. To minimize risk for launch, Instead of updating to the latest verion, we would like to backport (get the fix into the version we have) this and the following marketing promotion module change - https://github.com/VirtoCommerce/vc-module-marketing/issues/20

Is this possible?  Here's the version that we are on...  
![image](https://user-images.githubusercontent.com/37384557/45375014-cc8e6600-b5c1-11e8-95aa-421bc549adda.png)

**Comment by tatarincev** [comment]
@emathavan I think the most right choice is it will update Marketing and DynamicExpressions modules to the latest versions :)

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
