### ISSUE TITLE
Marketing module - Add ability to present user selected gift (1 from up to 10)

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-marketing#39]
As a Marketing Manager i'm trying to create new marketing campaign
When I create new condition to get a new product
Then I will have possibility to select set of the products(up to 10) 

Example:
If client buys more the 1000 kr and less then 2000 kr he receives 1 gift by his preference from 3 proposed
If client buys more then 2000 kr he gain another 1 gift from 5 proposed(more valuable).

Client could select only 1 from M (where M is up to 10), not N from M.

Proffs BO requests current functionality and it will be great if this issue could be estimated preliminary.
Not highest priority, but still quite interesting for client. 
I believe current feature will be interesting for other Business Owners aswell.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
