### ISSUE TITLE
Allow user to pick up time & timezone of promotion start and end dates

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-marketing#4]
Currently we set 00:00:00 and 23:59:59 of current user timezone to start and end dates respectively (see VirtoCommerce/vc-platform#956). The best solution is to allow user pick up time & timezone of promotion start and end dates.

**Comment by tatarincev** [comment]
It seems this already done.
You may reopen this issue if it has been closed in error.
![image](https://user-images.githubusercontent.com/7566324/71513648-df56a800-28a3-11ea-897e-cdf47bec3683.png)
