### ISSUE TITLE
Add mechanism(priority field) to decide with content publishing item to reflect from several product item

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-marketing#42]
**Environment:**
https://pm-admin-qc.azurewebsites.net/#/workspace/marketing
**Steps to reproduce:**
1. Add 2 active content publishing items or 1 more for currently existing content item.
2. Wait for 20 minutes to apply current content publishing items

**Expected results:**
Newly added content publishing items will be applied for specified period.
**Actual results:**
User do not understand why one of publishing item is applied and why another is not applied.
It should be clear rules, may be priority how to be 100% sure, that your publishing items will be applied not any other.
Because edit of publishing items doesn't work, user have to create new and new items.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
