### ISSUE TITLE
Long placeholder names are not visible for user 

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-marketing#43]
**Environment** - https://staging.proffsmagasinet.se
**Steps to reproduce:**
1. Open any publishing item from Marketing->Dynamic content ->Content publishing->Select Any->Content placeholder

**Expected results:**

User could see full name of placeholder

**Current results:**
For long names it is impossible to see even on full screen full name
We have ~ 8 similar names and they different only in last symbols

![image](https://user-images.githubusercontent.com/21069289/46084490-153e4580-c1a4-11e8-9fa1-32deb0811e1a.png)

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
