### ISSUE TITLE
For more than 1 condition it is impossible to edit 2nd and further conditions of Marketing campaign

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-marketing#44]
**Environmen**t : https://proffs-dev-admin.azurewebsites.net

**Steps to reproduce:**
1. Create Promotion with Condition Card SubTotal
2. Add sub-condition (From 1500 to 3000):
      2.1    If ALL of the following conditions are true then
      2.2    Add sub condition card sub-total atleast 1500
      2.3    Add sub condition card sub-total less than 3000
**VIDEO:** 

[Defect_For_Genia.zip](https://github.com/VirtoCommerce/vc-module-marketing/files/2441386/Defect_For_Genia.zip)

**Expected results:**
Conditions will be created.
**Actual results:**
For step 2.3 we could not change 2nd sub-condition, 1st subcondition is changed

**Remark:**
There is a workaround, to use BETWEEN sub-condition, which works fine. Not critical issue.

**Comment by yecli** [comment]
[v2.13.3](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/releases/tag/v2.13.3)
