### ISSUE TITLE
Improvement to Promotions - Priority of Reward should be allowed across both Absolute and Relative cart reward promos

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-module-marketing#46]
**Issue**
Regarding Marketing promotions module and the use of Priority:  Absolute vs Relative cart rewards are handled independent from each other when it comes to prioritization. 

For an absolute reward ($ off cart subtotal), the reward remains at the cart level and is applied across all items in the cart on the Storefront. However a relative reward (% off cart subtotal) gets converted into item level rewards and is applied individually to each item in the cart on the Platform. 

Problem is that there is currently no way to apply the priority at the storefront as that value is not passed forward. So the take away is that currently priority is only used to order rewards of exactly the same type

**Expected Behaviour**
Current behaviour is not very predicatable.  Priority functionality should be universal and apply to both types of rewards (Absolute vs Relative cart)

**Comment by tatarincev** [comment]
@emathavan Please read this article https://virtocommerce.com/docs/vc2userguide/marketing/combine-active-promotions it will help you better understand how the combination of  promotions works.
The reward type Relative or Absolute doesn't affect the priority of promotions.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
