### ISSUE TITLE
Content publishing condition "Gender" doesn't work properly

### ISSUE THREAD

**Issue by 5309** [VirtoCommerce/vc-module-marketing#51]
How to reproduce:

 - Go to [Demo storefront / theme electonics](https://demo.virtocommerce.com/Electronics/en-US/), sign in under the user who has gender setting = Male 
 - You will see a banner

![image](https://user-images.githubusercontent.com/30014191/50885485-6eaf4500-1420-11e9-94cb-8cb9ec7d27ed.png)

 - Than go to [Marketing module](https://admin-demo.virtocommerce.com/#/workspace/marketing) / Dynamic content / Content publishing / "Electronics store main page slider"; put a condition "Gender = Male":

![image](https://user-images.githubusercontent.com/30014191/50885746-247a9380-1421-11e9-8f35-84e787cc728a.png)

 - Go back to [Demo storefront / theme electonics](https://demo.virtocommerce.com/Electronics/en-US/) under the same male user

Expected behavior:
 - the banner is visible for the male user

Current behavior:
 - The banner is invisible:
![image](https://user-images.githubusercontent.com/30014191/50885831-673c6b80-1421-11e9-9722-71bbf0d35d98.png)

Here are user's settings:
(admin / Contacts / contact dynamic properties => Sex = "Male")
![image](https://user-images.githubusercontent.com/30014191/50885350-0d877180-1420-11e9-8d6b-2a697a67d7c6.png)

**Comment by tatarincev** [comment]
You might achieve this behavior by using  another way through `UserGroups`.  The latest DynamicExpressions and Storefront versions support this scenario.
![dynamic-content-user-groups](https://user-images.githubusercontent.com/7566324/51117576-e57c8180-1816-11e9-8c7d-9b28483efa8d.gif)

**Comment by 5309** [comment]
Now it is possible to use a publishing condition: "Shopper profile" / "User group contains" to see how dynamic content publishing conditions work.
