### ISSUE TITLE
To add more than 1 product/catalog to marketing promotion condition

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-marketing#54]
**Initial problem statement:**
Marketing module. Dynamic promotions.
Steps:
Open current promotion and try to add few(many) items (product or category)
Expected results:
It could be possible to add from 1 blade more than 1 item
Current results:
It is possible to add only 1.

Business priority for this task is low.
![image](https://user-images.githubusercontent.com/21069289/52070207-fa804100-2588-11e9-95d1-b0014671a56a.png)

**Functional requirements:**
Need to add ability to add multiple products into one promotion condition.

![image](https://user-images.githubusercontent.com/15610352/52224388-bca55480-28c9-11e9-8587-54304bb17820.png)

After clicking on select product, following blade should appear 
![image](https://user-images.githubusercontent.com/15610352/52224969-19edd580-28cb-11e9-83e9-e218ab23a5e5.png)
Similar blade in sitemaps:
![image](https://user-images.githubusercontent.com/15610352/52283100-b07dcd80-2983-11e9-99ea-48248e0e88ae.png)

When we press Add button, existing Catalog item select blade **with multiselect** enabled should appear.
![image](https://user-images.githubusercontent.com/15610352/52224660-5d940f80-28ca-11e9-9dba-489756d56991.png)

After selected required items and pressing "Pick selected" these items should appear in the Catalog condition list.

**Technical details:** 
1. vc-module-dynamic-expressions: Extend [ConditionEntryIs](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/d47b6e0c4b963643748d154d228dee50855ef287/VirtoCommerce.DynamicExpressionsModule.Data/Promotion/Conditions/CatalogConditions/ConditionEntryIs.cs) object with properties to store multiple ProductIds:
        public string[] ProductIds { get; set; }
        public string[] ProductNames { get; set; }

2. Add extension method
         public static bool IsItemInProducts(this PromotionEvaluationContext context, string[] productIds)
to PromotionEvaluationContextExtension for check if context productId contains in array of product Ids (e.g. [IsItemInProduct](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/ce8da82466f61bbe785042419f3dcb1440fe030d/VirtoCommerce.DynamicExpressionsModule.Data/Promotion/Helpers/PromotionEvaluationContextExtension.cs#L102)).

3. Add logic in [GetConditionExpression()](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/d47b6e0c4b963643748d154d228dee50855ef287/VirtoCommerce.DynamicExpressionsModule.Data/Promotion/Conditions/CatalogConditions/ConditionEntryIs.cs#L19) for their support using  method described in step 2 . Support backward compatibility for conditions having only ProductId and ProductName.

4. Implement new blade in vc-module-marketing (maybe later it could be moved to catalog module) with product list that shows product Picture, SKU and name; 
Call catalog item select blade from it for adding items (like in [promotionExpressionsController.openItemSelectWizard](https://github.com/VirtoCommerce/vc-module-marketing/blob/a6f4dc486bbb1b3d31c05c69ad0529f9b185712e/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-expressions.js#L8), but need to add multiselect support using showCheckingMultiple and selectedItemIds options of 'virtoCommerce.catalogModule.catalogItemSelectController')
Similar blade in sitemaps [link](https://github.com/VirtoCommerce/vc-module-sitemaps/blob/master/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-detail.tpl.html)

5. Call this new blade in product picker for [ConditionEntryIs template](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/ab84b2159b1cbf4979da3634d5b94f8243258866/VirtoCommerce.DynamicExpressionsModule.Web/Scripts/all-templates.html#L35). 

6. Add tests for multiple products scenario by extending [vc-module-dynamic-expressions tests](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/d47b6e0c4b963643748d154d228dee50855ef287/VirtoCommerce.DynamicExpressionsModule.Test/EvaluationTestDataGenerator.cs#L112)

**Comment by sansey2k** [comment]
Marketing module. Dynamic promotions.
Steps:
Open current promotion and try to add few(many) items (product or category)
Expected results:
It could be possible to add from 1 blade more than 1 item
Current results:
It is possible to add only 1.

Business priority for this task is low.

**Comment by blazemachine** [comment]
Done. You may watch the result in this file.
![Demonstration the new functionality](https://user-images.githubusercontent.com/43133766/54377125-566cd800-46a6-11e9-9f88-dd403c6afc6c.gif)

**Comment by yecli** [comment]
Multiple conditions would work only with https://github.com/VirtoCommerce/vc-module-dynamic-expressions/issues/12

**Comment by yecli** [comment]
[v2.17.5](https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.5)
