### ISSUE TITLE
Incorrect promotion coupon max usages logic

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce/vc-module-marketing#60]
https://github.com/VirtoCommerce/vc-module-marketing/blob/88c80b76a33928e721aaca23ecf542104125172b/VirtoCommerce.MarketingModule.Data/Promotions/DynamicPromotion.cs#L129

More or equals comparison gives one additional promo coupon usage when Maximum uses number == Total uses count.

**Comment by yecli** [comment]
Released in [v2.17.6](https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.6).
