### ISSUE TITLE
StoreId query issue

### ISSUE THREAD

**Issue by vanzegbroecke** [VirtoCommerce/vc-module-marketing#62]
Implementations of IMarketingPromoEvaluator create PromotionSearchCriteria with StoreIds = new[] { promoContext.StoreId } but this has undesired behaviour if promoContext.StoreId is null.

**Comment by yecli** [comment]
As i understand now PromotionSearchCriteria with StoreIds = new[] { promoContext.StoreId }  search returns all promotions where Store is not set. It seems expected to me.

**Comment by vanzegbroecke** [comment]
If the promotion always has to have a store yes. But then I would expect the same behaviour if I set store to null in the PromotionSearchCriteria, which is not the case.

**Comment by yecli** [comment]
We could have [0..n] stores defined for promotion.
Having empty store for promotion means it is not linked to specific stores - so it could be used by any store.
[This logic](https://github.com/VirtoCommerce/vc-module-marketing/blob/a6f4dc486bbb1b3d31c05c69ad0529f9b185712e/VirtoCommerce.MarketingModule.Data/Services/MarketingSearchServiceImpl.cs#L62) handles it.

There are 2 different cases:
1 - `PromotionSearchCriteria.StoreIds = new[] { null }`
2 - `PromotionSearchCriteria.StoreIds = null` or `PromotionSearchCriteria.StoreId = null` (old condition not supporting multiple stores).
In the 1st we want to get all common promotions, in the 2nd we want to get all promotions without Store restriction at all.

Now using `IMarketingPromoEvaluator.EvaluatePromotion(IEvaluationContext context)` we cannot get the second case, we always use the first one. Is it a problem?

Could you describe the real use case when promoContext.StoreId = null (which is not the case with standard storefront) and you want to get all promotions?

**Comment by tatarincev** [comment]
@yecli More correct logic will be take for  evaluation all promotions if store is not set.

**Comment by yecli** [comment]
Released in [v2.17.6](https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.6).
