### ISSUE TITLE
Allow to override and extend MarketingExportImport type

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-marketing#65]
**Problem:**
We have a new type for promotion derived from  `DynamicPromotion` that contains new fields. One of them represents a collections of URLs to images. We would like  to be able to export/import these images as binary data in JSON, the same way as it is done for catalog product images https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/ExportImport/CatalogExportImport.cs#L495 
**Solution**:
Make MarketingExportImport overridable and change methods to make it easy to do that kind of extension.

**Comment by yecli** [comment]
Released in [v2.17.6](https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.6).
