### ISSUE TITLE
Discount/Promotion improvements

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-marketing#7]
@Woland2k commented on [Mon Apr 11 2016](https://github.com/VirtoCommerce/vc-platform/issues/387)

Reintroduce priority and exclusivity for promotions so multiple discounts can be applied in correct order. Exclusivity should be used to prevent other promotions to be applied when the exclusive promotion is applied.

---

@aartiomov commented on [Tue Jun 13 2017](https://github.com/VirtoCommerce/vc-platform/issues/387#issuecomment-308061890)

From discussion with @tatarincev :
Current reward calculation implementation is based on choosing the best available reward (only one) that can be applied for the group (shipping, item, cart, payment). Changing it to apply more than one reward prioritizing them and adding exclusivity makes the reward calculation and applying more complex. There are several scenarios of reward application conflicts that has to be clarified:
1. same rule (condition) rewards application. Example: what if the cart total is $120 and there are 2 promotions for cart total. One is for cart totals over $90, another for cart totals over $100. Should both rewards be applied or there should be some logic added to choose only one promotion of the same rule?
2. two or more exclusive rewards that can be applied. Which one should be used? Based on the priority?
3. two or more rewards that can be applied with the same priority. What would be the application order? Probably it's not an issue.
4. promotions configuration UX. If we just add exclusivity switch and priority field to the promotion details it can be confusing on how all that configuration works with other currently active promotions. There could be some feedback for the user to display conflicts between different promotions. Can it be some process that would analyze promotions, similar to the process that analyzes catalog readiness?

---

@ArvidBauters commented on [Thu Jun 29 2017](https://github.com/VirtoCommerce/vc-platform/issues/387#issuecomment-311961324)

From discussion with @WimVergouwe : 
We are currently also looking into the possibility of multiple discounts. On a previous project (not in Virto) we created a structure with promotion folders which have a combination type. This combination type can be any of these 4 options:
- Largest Adjustment : Select the promotion that benefits the customer the most
- Smallest Adjustment : Select the promotion that benefits the customer the least
- First in Sort Order: Select the first promotion which applies.
- Accumulate: Select all promotions in the group which are valid in the current context and apply all rewards.

Is working with groups something you are considering?

---

@tatarincev commented on [Thu Jun 29 2017](https://github.com/VirtoCommerce/vc-platform/issues/387#issuecomment-311969584)

Yes, first three policies are looking good and even may be easily implemented. But the fourth is the most difficult, because with the composition of the rewards can affect the other promotion conditions. If you have some experience with it, please share to us we will appreciate it.

**Comment by Woland2k** [comment]
Implementation of combining promotions (not just one) as well as calculating "RunningTotal" when combining promotions is an important feature especially for the larger B2C and B2B sites.

**Comment by tatarincev** [comment]
Released 'Combination promotions stackable` policy.
https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.16.6
