### ISSUE TITLE
New content item Content type property is not working

### ISSUE THREAD

**Issue by tuviks** [VirtoCommerce/vc-module-marketing#94]
Ho to reproduce:
1. Add new content item
2. Select Html in Content type
3. Fill Html
4. Save

In database this property is null:
![image](https://user-images.githubusercontent.com/17646910/81429036-e2bd4280-9165-11ea-94ec-c31b6c768291.png)
![image](https://user-images.githubusercontent.com/17646910/81429237-2dd75580-9166-11ea-96f7-b056117b6bf6.png)

My slider is working only when I set this to Html from database

Version info:

Browser version: Google Chrome 81.0.4044.138
Platform version: 2.13.62
Module version: 2.17.9

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2256 has been created

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-marketing/releases/tag/v2.17.11
